# SITE CONFIGURATION
baseurl: ""
url: "http://jhower.github.io" # the base hostname & protocol for your site


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Jordan Hower"
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Designer, Developer, and Golfer.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "jhower91@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "https://github.com/jhower"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/jordan-hower-847a23a4/"
  pinterest: "jhower"
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-112376889-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 7
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]

theme: jekyll-theme-midnight

plugins:  [jekyll-paginate]
